require 'plugins.editor.nvim-tree'
require 'plugins.editor.nvim-compe'
require 'plugins.editor.markdown-preview'
require 'plugins.editor.nvim-autopairs'
require 'plugins.editor.tree-sitter'
require 'plugins.editor.galaxyline'
require 'plugins.editor.gitsigns'
require 'plugins.editor.nvim-colorizer'
